### ISSUE TITLE
Not showing MGN and OWL in Kovan

### ISSUE THREAD

**Issue by anxolin** [gnosis/dx-services-admin#13]
The OWL and MGN balances are not shown in Kovan network

![image](https://user-images.githubusercontent.com/2352112/57534181-c06ccb00-733f-11e9-9376-d781a8782e54.png)

**Comment by anxolin** [comment]
I think it's still not solved:

https://dx-services-admin.staging.gnosisdev.com/#/accounts/0xf4952239f5176ebf90c8f8c973fa38eaecc78af5

![image](https://user-images.githubusercontent.com/2352112/59094110-c1305700-8915-11e9-8a07-5956c915ab98.png)

**Comment by W3stside** [comment]
its empty cause there are no funds no?

**Comment by W3stside** [comment]
closed by #34
