### ISSUE TITLE
Not showing an information message when Metamask is not connected

### ISSUE THREAD

**Issue by luarx** [gnosis/dx-services-admin#18]
If I open the project website and I don't have my Metamask wallet connected, **the main screen is empty and doesn't show any message about why it's empty**.

Sometimes I don't have my wallet connected and I think that there is an error...after a while I realize that :( 

Example:
![image](https://user-images.githubusercontent.com/22997139/58473677-87a76100-8149-11e9-9abc-5433a9d7691e.png)

**Comment by anxolin** [comment]
Nice!
