### ISSUE TITLE
Bots not being display for mainnet

### ISSUE THREAD

**Issue by anxolin** [gnosis/dx-services-admin#3]
I think it's because they fail to get the info from the API cause it's using the symbol instead of the address.

**Comment by W3stside** [comment]
according to David this is a backend routing issue, will close for now @anxolin

**Comment by W3stside** [comment]
> I think it's because they fail to get the info from the API cause it's using the symbol instead of the address.

Note - I did change the `token.symbol` to `token.address` to align with API changes
