### ISSUE TITLE
Show two sides of every market

### ISSUE THREAD

**Issue by anxolin** [gnosis/dx-services-admin#7]
![image](https://user-images.githubusercontent.com/2352112/56130367-f7d89980-5f84-11e9-86b1-42054e21027b.png)

We are only displaying one side of the auction for every market.

I think it's OK to show one row per market, but maybe we need two cols for a extended state that includes both sides.

Some fields are common, like start time

**Comment by W3stside** [comment]
`State: Direct` & `State: Inverse`?

**Comment by W3stside** [comment]
current implementation:
![Screenshot from 2019-04-15 16-25-38](https://user-images.githubusercontent.com/21335563/56145025-6cb6ce00-5f9b-11e9-9d7c-332a74bff6dd.png)

**Comment by W3stside** [comment]
potentiallly fixed in commit hash `bdfeeea875c1220a2c8206bdf4b4dbaca63c6a7b`
